install.packages('devtools')
install.packages('tidyverse')
install.packages('magrittr')
install.packages('httr')
install.packages('plumber')
install.packages('tidymodels')
install.packages('janitor')
install.packages('data.table')
install.packages('lubridate')
install.packages('dplyr')
install.packages('stringr')
install.packages('ISOweek')
install.packages('fastDummies')

devtools::install_github('rsprojeto/Rossmann')

